### ISSUE TITLE
startTracing() function call throws error

### ISSUE THREAD

**Issue by rajkumars82** [saikrishna321/taiko-diagnostics#234]
## Issue: startTracing() function call throws error

npm install taiko-diagnostics --save
taiko --plugin taiko-diagnostics
openBrowser()
[PASS] Browser opened
startTracing()
Uncaught startTracing is not defined

Versions
taiko Version: 1.0.11 (Chromium: 84.0.4143.0) RELEASE
taiko-diagnostics: 0.4.0
node: v12.18.0
OS: Windows 10

**Comment by saikrishna321** [comment]
Looks like this is because of change in behaviours which we did when autoloading of plugins was implemented…plugin apis are returned as an object with name taiko-<plugin>  <plugin> taken from the plugin name hence taiko-diagnostics has to accessed as diagnostics.startTracing()  in repl this way it works fine

**Comment by rajkumars82** [comment]
Thank you
